---
- name: configuramos cuentas para administrar mysql
  mysql_user:  
    name: "{{ mysql_users[0].name }}"  
    host: "{{ item }}"  
    password: "{{ mysql_users[0].password }}"  
    login_user: "{{ mysql_users[1].name }}"  
    login_password: "{{ mysql_users[1].password }}"
    check_implicit_admin: yes  
    priv: "*.*:ALL,GRANT"
  with_items: 
  - "{{ ansible_hostname }}"  
  - 127.0.0.1  
  - ::1  
  - localhost

- name: creamos una base de datos con nombre testdb
  mysql_db: 
    name: testdb
    state: present
    login_user: "{{ mysql_users[1].name }}"
    login_password: "{{ mysql_users[1].password }}"

- name: copiamos un dump que tenemos para insertar en testdb
  copy:
    src: dump.sql
    dest: /tmp/dump.sql

- name: insertamos los datos del dump al testb
  mysql_db: 
    name: testdb
    state: import
    target: /tmp/dump.sql
    login_user: "{{ mysql_users[1].name }}"
    login_password: "{{ mysql_users[1].password }}"


