apiVersion: v1
kind: PersistentVolume
metadata:
  name: rundeck-pv
  labels:
    type: local
spec:
  storageClassName: standard
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/rundeck/data"