apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: rundeck-pvc
spec:
    storageClassName: standard
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 8Gi