---
- hosts: "{{ hosts }}"
  become: true
  tasks:
    - name: validar conexion a apache
      block:
        - uri:
            url: "http://{{ hosts }}"
      rescue:
        - service:
            name: httpd
            state: started
      always:
        - uri:
            url: "http://{{ hosts }}"
      
