---
- hosts: "{{ hosts }}"
  become: true
  tasks:
    - name: get files
      block:
      - uri:
          url: "http://{{ hosts }}"
      rescue:
        - debug:
            msg: "Debes levantar apache"
      always:
        - debug:
            msg: "Siempre ejecuto esto"
       
