---
- hosts: "{{ hosts }}"
  become: true
  tasks:
    - name: install apache
      package: 
        name: httpd
        state: latest
      tags: install
    - name: start and enable httpd
      service:
        name: httpd
        state: started
        enabled: yes
      tags: config
    - name: add a line to index.html
      copy:
        dest: /var/www/html/index.html
        content: |
          <html>
          <body>
          <h1>It works!</h1>
          Que bonito!
          Que Bonito!
          quE bOnitO!
          </body>
      tags: config
    - name: uninstall apache
      package: 
        name: httpd
        state: absent
      tags: uninstall
