---
- hosts: "{{ hosts }}"
  become: true
  tasks:
  - name: copiar un fichero estatico
    copy:
      src: /tools/git_repositories/ansible_rlujan/awx_labo_linux/test.conf
      dest: "/var/tmp/test.conf"
      owner: root
      group: root
      mode: '0644'
  - name: fichero de configuracion dinamico
    template:
      src: /tools/git_repositories/ansible_rlujan/awx_labo_linux/template_ejemplo.j2
      dest: "/var/tmp/test2.conf"
      owner: root
      group: root
      mode: '0644'
