---
- hosts: "{{ hosts }}"
  become: true
  tasks:
    - name: create dir /var/tmp/prueba_when
      file: 
        path: /var/tmp/prueba_when
        state: directory
      when: ansible_default_ipv4.address == "192.168.17.101"
