---
- hosts: "{{ hosts }}"
  become: true
  tasks:
   - name: "{{ accion }} service {{ servicio }}"
     service:
      name: "{{ servicio }}"
      state: "{{ accion }}"
     when: servicio is defined and accion is defined
      
